query:
  name: test-filter-query
  # type: dsl
  where: |-
    (
      message.security["com.optum.exts.eligibility.model.common.Security"].securitySourceSystemCode.string == 'cdb'
    )
    and 
    (
      (
        len(message.memberships.array) > 0
      ) 
      and 
        any
        (
          message.memberships.array[:], 
          (
            #.hContractId.string in ['H2226', 'R7444']
          ) 
          and 
          (
            (
              #.packageBenefitPlanCode.string in ['001', '002', '003', '004']
            ) 
            and 
            (
              #.segmentId.string in ['null', '001', '002', '003', '004']
            ) 
            and 
              any
              (
                #.membershipGroupData.array[:], 
                (
                  #.groupNumber.string in [ '12345', '100', '97008', '97007', '97006', '97005', '97004', '97003', '12830', 'null', '*']
                )
              )
              and 
              (
                (
                  #.effectiveDate.string > '2020-12-31'
                ) 
                or 
                (
                  #.effectiveDate.string > '2021-12-31'
                ) 
                or
                (
                  #.effectiveDate.string > '2022-12-31'
                )
              )
            )
          )
        )