query:
  name: test-filter-query
  # type: dsl
  where: |-
    (
      (
        (
          any
          (
            message.memberships.array[:], 
            (
              (
                (
                  groupExpression
                  (
                    ['#.hContractId.string','#.packageBenefitPlanCode.string','#.segmentId.string','#.groupNumber.string','#.effectiveDate.string'], 
                    ['eq',' eq',' eq'], 
                    ['H0169,001,null,*,2020-12-31']
                  )
                )
              )
            )
          )
        )
      )
    )