query:
  name: solutran
  where:
      # field:
      #   path: message.memberships.array
      #   type: array_element
      #   # type: array 
      # function:
      #   name: len
      #   field_path: message.memberships.array
      # len:
      #   field_path: message.memberships.array
      # operator: gt
      # value : 0
      field_path: message.memberships.array
      operator: len_gt
      # operator: gt
      value : 0
      # gt:
      #   len: message.memberships.array
      #   value: 0
      and:
        - 
          __len:
            field_path: message.memberships.array
          operator: gt
          value: 0
          __any:
            field_path: message.value.memberships.array[:]
            # array_field_path: message.value.memberships.array
            predicate:
              field_path: "#.hContractId.string"
              # array_element_field_path: ".hContractId.string"
              operator: in
              value:
                - H2226
                - R7444
              and:
                - field_path: "#.packageBenefitPlanCode.string"
                  operator: in
                  value:
                    - "001"
                    - "002"
                    - "003"
                    - "004"
                - field_path: "#.segmentId.string"
                  operator: in
                  value:
                    - "null"
                    - "001"
                    - "002"
                    - "003"
                    - "004"
                - function:
                    name: any #any_element_match
                    argument:
                      field_path: "#.membershipGroupData.array[:]"
                    predicate:
                      field_path: "#.groupNumber.string"
                      operator: in
                      value:
                        - "12345"
                        - "100"
                        - "97008"
                        - "97007"
                        - "97006"
                        - "97005"
                        - "97004"
                        - "97003"
                        - "12830"
                        - "null"
                        - ""
                        - "*"
                - or:
                  - field_path: "#.effectiveDate.string"
                    operator: gt
                    value: "2020-12-31"
                  - field_path: "#.effectiveDate.string"
                    operator: gt
                    value: "2021-12-31"
                  - field_path: "#.effectiveDate.string"
                    operator: gt
                    value: "2022-12-31"
