query:
  name: test
  where:
    message.value.security.securityAlt1SourceSystemCode.string:
      eq: CDB
    and:
      - all_array_elements_pass_predicate:
          argument:
            field_path_to_array: message.value.security["com.optum.exts.eligibility.model.common.Security"].securityPermissionInt.array
          predicate:
            field_path_to_array_element: .securityPermissionValue.int
            in:
              - 2
              - 5
              - 0
              - 3
              - 1
              - 7
